[zh-cn]
    languageName = "简体中文"
    title        = "MisakaTao's Blog"
    weight       = 1

    [zh-cn.params.sidebar]
        subtitle = "记录技术与生活"

[en]
    languageName = "English"
    title        = "MisakaTao's Blog"
    weight       = 2

    [en.params.sidebar]
        subtitle = "Tech & Life"
